env:
  browser: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  accessor-pairs: error
  array-bracket-spacing:
    - error
    - never
  array-callback-return: error
  arrow-body-style: 'off'
  arrow-parens:
    - error
    - as-needed
  arrow-spacing:
    - error
    - after: true
      before: true
  block-scoped-var: error
  block-spacing:
    - error
    - always
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true
  callback-return: error
  camelcase: error
  comma-dangle:
    - error
    - only-multiline
  comma-spacing:
    - error
    - after: true
      before: false
  comma-style:
    - error
    - last
  complexity: error
  computed-property-spacing:
    - error
    - never
  consistent-return: error
  consistent-this: error
  curly: 'off'
  default-case: 'off'
  dot-location:
    - error
    - property
  dot-notation:
    - error
    - allowKeywords: true
  eol-last: error
  eqeqeq: error
  func-call-spacing: error
  func-names: 'off'
  func-style:
    - error
    - declaration
  generator-star-spacing: error
  global-require: error
  guard-for-in: error
  handle-callback-err: error
  id-blacklist: error
  id-length: 'off'
  id-match: error
  indent: 'off'
  init-declarations: 'off'
  jsx-quotes: error
  key-spacing: error
  keyword-spacing:
    - error
    - after: true
      before: true
  linebreak-style:
    - error
    - unix
  lines-around-comment: 'off'
  max-depth: error
  max-len:
    - error
    - ignorePattern: '^import|^export'
      ignoreUrls: true
      ignoreTrailingComments: true
  max-lines: error
  max-nested-callbacks: error
  max-params: error
  max-statements:
    - error
    - max: 20
  max-statements-per-line: 'off'
  multiline-ternary: error
  new-parens: error
  newline-after-var: 'off'
  newline-before-return: 'off'
  newline-per-chained-call: error
  no-alert: error
  no-array-constructor: error
  no-bitwise: error
  no-caller: error
  no-catch-shadow: error
  no-confusing-arrow: error
  no-console:
    - error
    - allow: ['error', 'warn']
  no-continue: error
  no-div-regex: error
  no-duplicate-imports: error
  no-else-return: error
  no-empty-function: error
  no-eq-null: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-extra-parens: error
  no-floating-decimal: error
  no-global-assign: error
  no-implicit-coercion: error
  no-implicit-globals: error
  no-implied-eval: error
  no-inline-comments: 'off'
  no-invalid-this: 'off'
  no-iterator: error
  no-label-var: error
  no-labels: error
  no-lone-blocks: error
  no-lonely-if: error
  no-loop-func: error
  no-magic-numbers: 'off'
  no-mixed-operators: error
  no-mixed-requires: error
  no-multi-spaces: 'off'
  no-multi-str: error
  no-multiple-empty-lines: error
  no-negated-condition: error
  no-nested-ternary: error
  no-new: error
  no-new-func: error
  no-new-object: error
  no-new-require: error
  no-new-wrappers: error
  no-octal-escape: error
  no-param-reassign: error
  no-path-concat: error
  no-plusplus: error
  no-process-env: error
  no-process-exit: error
  no-proto: error
  no-prototype-builtins: error
  no-restricted-globals: error
  no-restricted-imports: error
  no-restricted-modules: error
  no-restricted-syntax: error
  no-return-assign: error
  no-script-url: error
  no-self-compare: error
  no-sequences: error
  no-shadow: error
  no-shadow-restricted-names: error
  no-spaced-func: error
  no-sync: error
  no-tabs: error
  no-template-curly-in-string: error
  no-ternary: error
  no-throw-literal: error
  no-trailing-spaces: error
  no-undef-init: error
  no-undefined: error
  no-underscore-dangle: 'off'
  no-unmodified-loop-condition: error
  no-unneeded-ternary: error
  no-unsafe-negation: error
  no-unused-expressions: error
  no-unused-vars:
    - error
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
  no-use-before-define: 'off'
  no-useless-call: error
  no-useless-computed-key: error
  no-useless-concat: error
  no-useless-constructor: error
  no-useless-escape: error
  no-useless-rename: error
  no-var: error
  no-void: error
  no-warning-comments: error
  no-whitespace-before-property: error
  no-with: error
  object-curly-newline: 'off'
  object-curly-spacing:
    - error
    - always
  object-property-newline: error
  object-shorthand: error
  one-var: 'off'
  one-var-declaration-per-line: error
  operator-assignment: error
  operator-linebreak: error
  padded-blocks: 'off'
  prefer-arrow-callback: 'off'
  prefer-const: error
  prefer-reflect: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  quote-props: 'off'
  quotes:
    - error
    - single
  radix: error
  require-jsdoc: 'off'
  rest-spread-spacing:
    - error
    - never
  semi: error
  semi-spacing: error
  sort-imports: 'off'
  sort-keys: 'off'
  sort-vars: error
  space-before-blocks: error
  space-before-function-paren: 'off'
  space-in-parens:
    - error
    - never
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment: 'off'
  strict: error
  template-curly-spacing:
    - error
    - never
  unicode-bom:
    - error
    - never
  vars-on-top: error
  wrap-iife: error
  wrap-regex: error
  yield-star-spacing: error
  yoda: error
